# Generated by Django 4.1.7 on 2023-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
